# --- 기본 설정 ---
baseURL = 'https://edumelleda-max.github.io/'
languageCode = 'ko-kr'
title = '리뷰의 정석'
theme = 'PaperMod'
# --- 페이지네이션 설정 (이 부분이 수정되었습니다) ---
[pagination]
pagerSize = 5 # 한 페이지에 보일 글 개수

# --- 언어 설정 (중요) ---
defaultContentLanguage = "ko"
defaultContentLanguageInSubdir = false

# --- 메뉴 설정 ---
# 블로그 상단에 보일 메뉴들입니다.
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "글 목록"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "소개"
    url = "/about/"
    weight = 2
  [[menu.main]]
    identifier = "privacy"
    name = "개인정보처리방침"
    url = "/privacy/"
    weight = 3

# --- 블로그 상세 정보 (SEO 및 꾸미기) ---
[params]
  author = "리뷰의 정석"
  description = "초보자가 겪은 장비 구매 스토리. 복잡한 정보 속에서 길을 잃은 당신이 어제의 나의 모습니다. 초보지만 멋모를 때의 명쾌한 해답을 공유합니다."
  defaultTheme = "auto"  # 방문자 시스템 설정에 따라 라이트/다크 모드 자동 변경
  ShowReadingTime = true # 글 읽는 시간 표시
  ShowShareButtons = true # 공유 버튼 표시
  ShowPostNavLinks = true # 이전/다음 글 링크 표시

  # --- 소셜 아이콘 설정 ---
  # 필요 없는 것은 줄을 지우거나, #으로 주석 처리하세요.
  [[params.socialIcons]]
    name = "email"
    url = "edumelleda@gmail.com" # 본인 이메일 주소로 변경
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/edumelleda-max" # 본인 GitHub 주소
  # [[params.socialIcons]]
  #   name = "instagram"
  #   url = "https://instagram.com/example"